type: GEMM

matrix:
  M: 32
  K: 32
  N: 32

tiling:
  T_M: 16
  T_K: 16
  T_N: 16

unroll:
  u_M: 1
  u_K: 1
  u_N: 1

arch:
  mapping_policy: bank_affine  # or static/manual if needed
  kernel_name: basic_kernel

execution:
  rounds: 1
  parallel: false   # easier for tracing single PU
